import { chromium } from 'playwright'
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
const p = await b.newPage({ viewport: { width: 1360, height: 980 } })
await p.addInitScript(() => {
  localStorage.setItem('agent_url', 'https://mock-agent.test')
  localStorage.setItem('agent_secret', 'x')
  sessionStorage.setItem('tune_tab', 'risk')
})
const J = (o) => ({ status: 200, contentType: 'application/json', body: JSON.stringify(o) })
await p.route('https://mock-agent.test/**', route => {
  const u = route.request().url()
  if (u.includes('/state/config')) return route.fulfill(J({ scan_enabled: true, analyze_enabled: true, autotrade_enabled: true, symbols: [{ symbol: 'EURUSD', enabled: true }] }))
  if (u.includes('/state/risk-config')) return route.fulfill(J({ effective: { perTradeRiskPct: 0.01, dailyLossPct: 0.03, minRR: 1.5, maxOpenPositions: 5, symbolCooldownMinutes: 240, maxConsecutiveLosses: 3, cooldownMinutes: 60, minSLDistancePct: 0.15, maxMarginUsagePct: 0.5, kellyFraction: 0.25 }, derived: { balance: 49791.7, leverage: 200, daily_cap_usd: 1493.75, per_trade_budget_usd: 497.92 } }))
  if (u.includes('/state/autotrade-timeframes')) return route.fulfill(J({ timeframes: ['4h', '1d'] }))
  if (u.includes('/state/fib-rsi-filter')) return route.fulfill(J({ on: false }))
  if (u.includes('/state/symbol-map')) return route.fulfill(J({ map: { EURUSD: 1, GBPUSD: 2 } }))
  return route.fulfill(J({}))
})
await p.goto('http://localhost:4173/tune', { waitUntil: 'networkidle' })
await p.waitForTimeout(900)
// open the Min risk:reward dropdown to show the styled menu
await p.locator('button:has-text("1.5 — default")').first().click()
await p.waitForTimeout(300)
await p.screenshot({ path: 'std-risk.png', fullPage: false })
console.log('editable value boxes:', await p.locator('input[type=number][aria-label*="value"]').count())
console.log('sliders:', await p.locator('input[type=range]').count())
console.log('styled menu open:', await p.locator('[role=listbox]').count())
console.log('custom row:', await p.locator('input[placeholder="Custom…"]').count())
console.log('active option check:', await p.locator('[role=option][aria-selected=true]').count())
await b.close()
