// node --test agent/lib/backtest-report.test.js

import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { reportFilename, sgDateStamp, renderBacktestReport, verdictFor, reportsDir, saveBacktestReport } from './backtest-report.js'

// 2026-07-09 02:00 UTC = 10:00 SGT same day; 2026-07-08 17:00 UTC = 09 July 01:00 SGT
const utcMorning = new Date('2026-07-09T02:00:00Z')
const utcEvening = new Date('2026-07-08T17:00:00Z')

test('sgDateStamp uses Singapore time, not UTC', () => {
  assert.equal(sgDateStamp(utcMorning), '2026-0709')
  assert.equal(sgDateStamp(utcEvening), '2026-0709') // already tomorrow in SGT
})

test('reportFilename starts at _00 and takes the next free serial', () => {
  assert.equal(reportFilename([], utcMorning), '2026-0709_00.html')
  assert.equal(reportFilename(['2026-0709_00.html', '2026-0709_01.html'], utcMorning), '2026-0709_02.html')
  // other days' files are ignored
  assert.equal(reportFilename(['2026-0708_05.html'], utcMorning), '2026-0709_00.html')
})

test('verdictFor mirrors the UI three-state logic', () => {
  assert.equal(verdictFor({ trades: 12, losses: 3, profitFactor: 1.5, totalProfitPct: 4 }).state, 'go')
  assert.equal(verdictFor({ trades: 3, losses: 1, profitFactor: 1.5, totalProfitPct: 2 }).state, 'thin')
  assert.equal(verdictFor({ trades: 12, losses: 3, profitFactor: 0.9, totalProfitPct: -2 }).state, 'no-go')
  assert.equal(verdictFor({ trades: 12, losses: 0, profitFactor: null, totalProfitPct: 5 }).state, 'go') // ∞ PF passes
})

test('renderBacktestReport is self-contained html with symbols and escaping', () => {
  const html = renderBacktestReport({
    ranAt: '2026-07-09T02:00:00.000Z', bars: 1000,
    symbols: {
      EURUSD: { results: { '4h': { trades: 12, losses: 3, profitFactor: 1.5, totalProfitPct: 4, winRatePct: 60, maxDrawdownPct: 2, barsUsed: 999 } } },
      'BAD<SYM>': { error: 'not offered <script>' },
    },
  }, '2026-0709_00.html')
  assert.match(html, /^<!doctype html>/)
  assert.match(html, /EURUSD/)
  assert.match(html, /GO/)
  assert.ok(!html.includes('<script>'), 'error text must be escaped')
  assert.ok(!/https?:\/\//.test(html.replace(/generated by/i, '')), 'no external resources')
})

test('reportsDir honours DB_PATH (persistent volume) and falls back to baseDir', t => {
  const prev = process.env.DB_PATH
  t.after(() => { if (prev === undefined) delete process.env.DB_PATH; else process.env.DB_PATH = prev })

  process.env.DB_PATH = '/data/agent.db'
  assert.equal(reportsDir('/ignored'), path.join('/data', 'backtest-results'))

  delete process.env.DB_PATH
  assert.equal(reportsDir('/srv/app'), path.join('/srv/app', 'backtest-results'))
  assert.equal(reportsDir(), path.join(process.cwd(), 'backtest-results'))
})

test('saveBacktestReport continues the serial across a populated dir (survives redeploy)', t => {
  const prev = process.env.DB_PATH
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'bt-report-'))
  t.after(() => {
    fs.rmSync(tmp, { recursive: true, force: true })
    if (prev === undefined) delete process.env.DB_PATH; else process.env.DB_PATH = prev
  })

  // Pretend the DB lives on the volume; reports must land beside it.
  process.env.DB_PATH = path.join(tmp, 'agent.db')
  const dir = reportsDir('/some/other/basedir')
  assert.equal(dir, path.join(tmp, 'backtest-results'))

  // Pre-populate as if written before a redeploy — serial must NOT reset.
  fs.mkdirSync(dir, { recursive: true })
  fs.writeFileSync(path.join(dir, '2026-0709_00.html'), 'x')
  fs.writeFileSync(path.join(dir, '2026-0709_01.html'), 'x')

  const now = new Date('2026-07-09T02:00:00Z') // 10:00 SGT, same stamp
  const { filename } = saveBacktestReport({ symbols: {} }, '/some/other/basedir', now)
  assert.equal(filename, '2026-0709_02.html')
  assert.ok(fs.existsSync(path.join(dir, filename)), 'report written into the DB_PATH dir')

  // Next save keeps counting.
  assert.equal(saveBacktestReport({ symbols: {} }, '/some/other/basedir', now).filename, '2026-0709_03.html')
})
